services:
  mongodb:
    image: mongo:7.0
    container_name: iips-deams-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: iips_deams
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
